try error("some exception") catch .